// Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
#![cfg(target_arch = "x86_64")]
/// Abstractions for a basic filtering of `CPUID`.
pub mod cpuid;
/// Abstractions for building a Global Descriptor Table (GDT).
pub mod gdt;
/// Helpers for setting up interrupt related registers.
pub mod interrupts;
/// MSR defines autogenerated from Linux: `arch/x86/include/asm/msr-index.h`.
pub mod msr_index;
/// Abstractions for building and filtering MSR (Model Specific Register).
pub mod msrs;
